import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import prisma from "@/lib/prisma";
import TermsAcceptForm from "@/components/TermsAcceptForm";

export default async function TermsPage() {
  const session = await getServerSession(authOptions);
  const user = session?.user?.id
    ? await prisma.user.findUnique({
        where: { id: String(session.user.id) },
        select: { termsAcceptedAt: true },
      })
    : null;
  const needsAcceptance = Boolean(session?.user?.id && !user?.termsAcceptedAt);
  return (
    <main>
      <div className="page-shell">
        <div className="stack" style={{ maxWidth: 860, margin: '40px auto' }}>
          <article className="card">
            <header className="card-head">
              <h1>Terms &amp; Conditions</h1>
              <div className="sub">Last updated: {new Date().toLocaleDateString()}</div>
            </header>

            <div className="stack">
              <section>
                <div className="planner-head">AI-generated content</div>
                <p className="muted">
                  Workouts, meal plans, and other recommendations in this app may be generated by AI.
                  These suggestions are informational only and may be incomplete, inaccurate, or
                  inappropriate for your personal circumstances.
                </p>
                <p className="muted">
                  Any meal cost or cost-per-serving figures shown in the app are AI-generated estimates,
                  not quotes or guarantees. Actual prices vary by store, region, brand, season, taxes,
                  and package size.
                </p>
                <p className="muted">
                  You are responsible for your own decisions and for using your best judgment.
                  Consult a qualified professional if you have any medical conditions, injuries,
                  dietary restrictions, or other concerns.
                </p>
              </section>

              <section>
                <div className="planner-head">User responsibility &amp; safety</div>
                <p className="muted">
                  You agree to exercise and follow nutrition guidance safely and at your own risk.
                  Stop immediately if you feel pain, dizziness, or discomfort, and seek medical advice.
                </p>
              </section>
              <section>
                <div className="planner-head">Not medical advice</div>
                <p className="muted">
                  The app does not provide medical advice, diagnosis, or treatment. The content is
                  for general informational purposes only and is not a substitute for professional
                  medical advice. Always seek the advice of a physician or qualified health provider
                  with any questions regarding a medical condition.
                </p>
              </section>
              <section>
                <div className="planner-head">General health guidelines</div>
                <p className="muted">
                  We aim to design workouts, meal-planning features, and adjustment logic with
                  reference to broadly recognized public health and fitness guidelines. This includes
                  using general safety guardrails for calorie targets, exercise volume, and gradual
                  progression where appropriate.
                </p>
                <p className="muted">
                  These guardrails are general in nature and may not be appropriate for your age,
                  body size, medications, injuries, health history, or other personal circumstances.
                  You remain responsible for deciding what is appropriate for you.
                </p>
              </section>
              <section>
                <div className="planner-head">Eligibility</div>
                <p className="muted">
                  You must be at least 18 years old, or the age of majority in your jurisdiction,
                  to use the app. By using the app, you represent that you meet this requirement.
                </p>
              </section>

              <section>
                <div className="planner-head">Photo guidelines</div>
                <p className="muted">
                  If you upload food photos, they must clearly show the meal or ingredients.
                  If we add a body composition estimator, any photos you upload must be non-explicit,
                  non-sexual, and appropriate for a general audience. Images should show standard
                  athletic or swimwear similar to what is acceptable at a public beach or gym.
                </p>
                <p className="muted">
                  Do not upload content that is illegal, pornographic, sexually explicit, violent,
                  hateful, harassing, or otherwise inappropriate. We may remove content or restrict
                  access for violations.
                </p>
                <p className="muted">
                  We use automated content moderation to screen images. Uploads that fail these
                  checks may be blocked or removed.
                </p>
              </section>
              <section>
                <div className="planner-head">Account security</div>
                <p className="muted">
                  You are responsible for maintaining the confidentiality of your account credentials
                  and for all activity under your account. Notify us immediately if you suspect
                  unauthorized access.
                </p>
              </section>
              <section>
                <div className="planner-head">User content</div>
                <p className="muted">
                  You retain ownership of content you upload, but you grant us a non-exclusive,
                  worldwide, royalty-free license to host, store, reproduce, and display it as
                  needed to operate and improve the app.
                </p>
              </section>
              <section>
                <div className="planner-head">Third-party services</div>
                <p className="muted">
                  The app may integrate with third-party services. We are not responsible for
                  third-party content, policies, or practices, and your use of those services is
                  subject to their terms.
                </p>
              </section>
              <section>
                <div className="planner-head">Disclaimers</div>
                <p className="muted">
                  The app and all content are provided on an &quot;as is&quot; and &quot;as available&quot; basis without
                  warranties of any kind, express or implied, including implied warranties of
                  merchantability, fitness for a particular purpose, and non-infringement.
                </p>
              </section>
              <section>
                <div className="planner-head">Limitation of liability</div>
                <p className="muted">
                  To the fullest extent permitted by law, we will not be liable for any indirect,
                  incidental, special, consequential, or punitive damages, or any loss of profits,
                  data, or goodwill, arising from or related to your use of the app.
                </p>
              </section>
              <section>
                <div className="planner-head">Termination</div>
                <p className="muted">
                  We may suspend or terminate your access to the app at any time if you violate these
                  terms or if required by law.
                </p>
              </section>
              <section>
                <div className="planner-head">Governing law</div>
                <p className="muted">
                  These terms are governed by the laws of the jurisdiction where we operate, without
                  regard to conflict of law principles.
                </p>
              </section>
              <section>
                <div className="planner-head">Changes</div>
                <p className="muted">
                  We may update these terms from time to time. Continued use of the app means you
                  accept the revised terms.
                </p>
              </section>
              {needsAcceptance && (
                <section>
                  <div className="planner-head">Accept terms</div>
                  <p className="muted">
                    You must accept these terms to continue using the app.
                  </p>
                  <TermsAcceptForm />
                </section>
              )}
              {session?.user?.id && !needsAcceptance && (
                <section>
                  <div className="planner-head">Status</div>
                  <p className="muted">You have already accepted these terms.</p>
                </section>
              )}
            </div>
          </article>
        </div>
      </div>
    </main>
  );
}
